twist_mux:
  ros__parameters:
    topics:
      joystick  : 
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 90

      controller:
        topic   : cmd_vel_ctrl
        timeout : 0.5
        priority: 70
      
      wall:
        topic   : cmd_route
        timeout : 0.5
        priority: 10

      braking:
        topic   : braking_vel
        timeout : 0.5
        priority: 10 
